### ISSUE TITLE
Bundle crashes TextMate with .editor config file generated by .net-sdk-preview

### ISSUE THREAD

**Issue by tamaracha** [Mr0grog/editorconfig-textmate#42]
Hi,

Microsoft has started to use the .editorconfig file as the configuration file for their code analysis rules in .net projects, and they have defined a bunch of custom properties starting with `dotnet_`. Some of these properties crash TextMate when they are included in the .editorconfig and a matching file is opened. I can't see how they differ from the other ones. If you have this example section in the .editorconfig and open a .cs file, nothing strange will happen. But if you uncomment the second property before opening the .cs file, TextMate crashes.

```toml
[*.cs]
# Parentheses preferences
dotnet_style_parentheses_in_arithmetic_binary_operators = always_for_clarity:silent
# dotnet_style_parentheses_in_other_binary_operators = always_for_clarity:silent
dotnet_style_parentheses_in_other_operators = never_if_unnecessary:silent
dotnet_style_parentheses_in_relational_binary_operators = always_for_clarity:silent
```

I have no idea how this makes sense, because I have no experience in C programming.

Thanks in advance
